# AdvancedHeal V1.0.0 by GamerMJay, licensed under Apache License 2.0!
#######

# Messages
heal: healCommand
heal-description: healCommand you
feed: feedCommand
feed-description: feedCommand you

run-ingame: "§c§lAdvancedHeal §r§8» §crun this command ingame!"
heal-message: "§c§lAdvancedHeal §r§8» §ayou have been healed"
feed-message: "§c§lAdvancedHeal §r§8» §aYour hunger has been satisfied"